# Generated by Django 5.1 on 2024-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_time_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='time_measurement',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
